import { useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { getChanges, getRules, getAddress } from "@/data";
import { hideInternalNote } from "@/lib/format";
import { StatusBadge } from "@/components/StatusBadge";
import { RequestAccessModal } from "@/components/RequestAccessModal";
import { Button } from "@/components/ui/button";
import { useAsOf } from "@/components/WorkspaceShell";
import { useLang } from "@/i18n";
export const Route=createFileRoute("/app/changes")({head:()=>({meta:[{title:"Statute Street: Change register"},{name:"description",content:"Legal changes and their tested address impact."},{property:"og:title",content:"Statute Street: Change register"},{property:"og:description",content:"Legal changes and their tested address impact."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Changes});
function Changes(){const {t}=useLang();const {date}=useAsOf();const [watch,setWatch]=useState("");const rules=getRules();return <div className="p-4 pb-24 lg:p-6"><h1 className="text-4xl font-semibold">{t.v2.changes.title}</h1><p className="mt-2 text-muted-foreground">{t.v2.changes.lead}</p><div className="mt-6 overflow-x-auto border border-border"><table className="w-full min-w-[1050px] text-left text-[13px]"><thead className="bg-secondary"><tr>{Object.values(t.v2.changes.cols).map(x=><th key={x} className="px-3 py-2">{x}</th>)}</tr></thead><tbody>{getChanges().map(c=>{const related=rules.filter(r=>c.notes.includes(r.team_rule_id));const status=related.some(r=>r.status==="pending")?"pending":related.some(r=>r.status==="failed")?"failed":related.some(r=>r.status==="not_yet_effective")?"not_yet_effective":"applies";const first=getAddress(c.affected_address_ids[0]||"");const note=hideInternalNote(c.notes);return <tr key={c.test_id} className="border-t border-border align-top hover:bg-secondary"><td className="px-3 py-3 font-mono font-semibold">{c.test_id}</td><td className="max-w-sm px-3 py-3"><p className="line-clamp-4">{note||t.address.reviewHidden}</p></td><td className="px-3 py-3">{[...new Set(related.map(r=>r.jurisdiction))].join(", ")||t.v2.changes.unavailable}</td><td className="px-3 py-3">{t.v2.changes.unavailable}</td><td className="px-3 py-3 font-mono">{related.map(r=>r.effective_date).filter(Boolean).join(", ")||t.v2.changes.unavailable}</td><td className="px-3 py-3"><StatusBadge kind={status}/></td><td className="px-3 py-3 font-mono">{c.affected_address_ids.length}</td><td className="px-3 py-3 font-mono">{c.conflict_flag_address_ids.length}</td><td className="px-3 py-3"><div className="flex gap-2">{first&&<Link to="/app/address/$id" params={{id:first.address_id}} search={{asof:date}} className="text-primary underline">{t.v2.changes.example}</Link>}<Button variant="link" className="h-auto p-0" onClick={()=>setWatch(c.test_id)}>{t.v2.changes.watch}</Button></div></td></tr>})}</tbody></table></div><RequestAccessModal open={Boolean(watch)} onClose={()=>setWatch("")} subject={watch}/></div>}
