import { createFileRoute, notFound } from "@tanstack/react-router";
import { getAddress, data, getSources } from "@/data";
import { resolveAddress } from "@/lib/resolve";
import { useAsOf } from "@/components/WorkspaceShell";
import { Button } from "@/components/ui/button";
import { useLang } from "@/i18n";
import { formatDate, formatTimestamp } from "@/lib/format";
export const Route=createFileRoute("/app/record/$id")({validateSearch:(s:Record<string,unknown>)=>({asof:typeof s.asof==="string"?s.asof:undefined,action:typeof s.action==="string"?s.action:undefined}),loader:({params})=>{const address=getAddress(params.id);if(!address)throw notFound();return{address}},head:()=>({meta:[{title:"Statute Street: Reliance record"},{name:"description",content:"A printable record of dated housing rule determinations."},{property:"og:title",content:"Statute Street: Reliance record"},{property:"og:description",content:"A printable record of dated housing rule determinations."},{property:"og:type",content:"article"},{name:"twitter:card",content:"summary"}]}),component:RecordPage});
function RecordPage(){const {address}=Route.useLoaderData();const search=Route.useSearch();const global=useAsOf();const date=search.asof||global.date;const {t,lang}=useLang();const result=resolveAddress(address,date,data);const items=Object.values(result.byCategory).flat().filter(i=>i.badge!=="failed");return <article className="print-document mx-auto max-w-4xl p-6 pb-24"><div className="no-print mb-6 flex justify-end"><Button onClick={()=>window.print()}>{t.v2.record.print}</Button></div><h1 className="text-4xl font-semibold">{t.v2.record.title}</h1><dl className="mt-6 grid gap-2 border-y border-border py-4 font-mono text-sm sm:grid-cols-2"><div><dt>{t.home.label}</dt><dd>{address.street_address}, {result.stack.city}, {address.state}</dd></div><div><dt>{t.v2.determination.asOf}</dt><dd>{formatDate(date,lang)}</dd></div>{search.action&&<div><dt>{t.v2.record.action}</dt><dd>{search.action}</dd></div>}<div><dt>{t.v2.record.generated}</dt><dd>{formatTimestamp(new Date().toISOString(),lang)}</dd></div></dl><h2 className="mt-8 text-2xl font-semibold">{t.v2.record.relied}</h2>{items.map(i=>{const s=getSources().find(x=>x.source_id===i.rule.source_doc_id);return <section key={i.rule.team_rule_id} className="mt-5 border-t border-border pt-4"><h3 className="text-xl font-semibold">{i.rule.title}</h3><p className="mt-2">{i.rule.requirement}</p><blockquote className="quote-block mt-3">{i.rule.quoted_span}</blockquote><p className="mt-2 font-mono text-xs">{i.rule.citation} · {i.rule.source_url}</p><p className="font-mono text-xs">{s?.retrieved_at?formatTimestamp(s.retrieved_at,lang):t.address.retrievalMissing}</p></section>})}<p className="mt-10 border-t border-border pt-4 text-sm">{t.banner}</p><p className="mt-10">{t.v2.record.reviewedBy}: ______________________________</p><p className="no-print mt-6 text-xs text-muted-foreground">{t.v2.record.notStored}</p></article>}
