import { useMemo, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { data, getAddresses, type Category } from "@/data";
import { resolveAddress } from "@/lib/resolve";
import { useAsOf } from "@/components/WorkspaceShell";
import { DeterminationRow } from "@/components/DeterminationRow";
import { Button, buttonVariants } from "@/components/ui/button";
import { useLang } from "@/i18n";
const maps:Category[][]=[["rent_increase_limits"],["algorithmic_rent_setting"],["screening_restrictions"],["application_screening_fees"],["security_deposits"],["just_cause_eviction"]];
export const Route=createFileRoute("/app/check")({validateSearch:(s:Record<string,unknown>)=>({asof:typeof s["asof"]==="string"?s["asof"]:undefined,address:typeof s["address"]==="string"?s["address"]:undefined}),head:()=>({meta:[{title:"Statute Street: Action check"},{name:"description",content:"Check the rules tied to one rental housing action."},{property:"og:title",content:"Statute Street: Action check"},{property:"og:description",content:"Check the rules tied to one rental housing action."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:ActionCheck});
function ActionCheck(){const {t}=useLang();const {date}=useAsOf();const search=Route.useSearch();const addresses=getAddresses();const [aid,setAid]=useState(search.address??"");const [action,setAction]=useState(0);const address=addresses.find(a=>a.address_id===aid);const result=useMemo(()=>address?resolveAddress(address,date,data):null,[address,date]);const items=result?maps[action]!.flatMap(c=>result.byCategory[c]):[];const binds=items.filter(i=>i.badge==="applies").length;const verdict=binds?t.v2.check.restricted(binds):items.some(i=>i.badge==="unknown")?t.v2.check.unknown:items.length>0&&items.every(i=>i.badge==="none")?t.v2.check.none:"";return <div className="mx-auto max-w-5xl p-4 pb-24 lg:p-6"><h1 className="text-4xl font-semibold">{t.v2.check.title}</h1><p className="mt-2 text-muted-foreground">{t.v2.check.lead}</p><div className="mt-6 grid gap-4 border-y border-border py-5 md:grid-cols-2"><label className="text-sm font-semibold">{t.v2.check.address}<select value={aid} onChange={e=>setAid(e.target.value)} className="mt-1 block w-full border border-input bg-background px-3 py-2 font-normal"><option value="">{t.v2.check.address}</option>{addresses.map(a=><option key={a.address_id} value={a.address_id}>{a.street_address}, {a.postal_city}</option>)}</select></label><label className="text-sm font-semibold">{t.v2.check.action}<select value={action} onChange={e=>setAction(Number(e.target.value))} className="mt-1 block w-full border border-input bg-background px-3 py-2 font-normal">{t.v2.check.actions.map((x,i)=><option key={x} value={i}>{x}</option>)}</select></label></div>{!address?<p className="mt-8 text-muted-foreground">{t.v2.check.choose}</p>:<><section className="mt-8 border-l-4 border-primary pl-4"><h2 className="text-2xl font-semibold">{verdict||t.v2.check.none}</h2>{items.some(i=>i.badge==="not_yet_effective")&&<p className="text-sm">{t.v2.check.notYet}</p>}{items.some(i=>i.badge==="pending")&&<p className="text-sm">{t.v2.check.pending}</p>}</section><div className="mt-6 border-t border-border">{items.map(i=><DeterminationRow key={i.rule.team_rule_id} item={i} address={address}/>)}</div><p className="mt-5 text-sm text-muted-foreground">{t.v2.check.caption}</p><div className="mt-5 flex gap-2"><Link to="/app/record/$id" params={{id:address.address_id}} search={{asof:date,action:String(action)}} className={buttonVariants()}>{t.v2.determination.recordReliance}</Link><Link to="/app/address/$id" params={{id:address.address_id}} search={{asof:date}} className={buttonVariants({variant:"outline"})}>{t.v2.check.openFull}</Link></div></>}</div>}
