import { createFileRoute, notFound } from "@tanstack/react-router";
import { getAddress, data } from "@/data";
import { resolveAddress } from "@/lib/resolve";
import { useAsOf } from "@/components/WorkspaceShell";
import { Button } from "@/components/ui/button";
import { useLang } from "@/i18n";
import { formatDate } from "@/lib/format";
const groups = [{ k: "rent", c: ["rent_increase_limits"] }, { k: "deposits", c: ["security_deposits"] }, { k: "ending", c: ["just_cause_eviction"] }, { k: "screening", c: ["screening_restrictions", "application_screening_fees"] }] as const;
export const Route = createFileRoute("/app/notice/$id")({ loader: ({ params }) => { const address = getAddress(params.id); if (!address) throw notFound(); return { address }; }, head: () => ({ meta: [{ title: "Statute Street: Tenant notice" }, { name: "description", content: "A printable rental housing rights notice by address." }, { property: "og:title", content: "Statute Street: Tenant notice" }, { property: "og:description", content: "A printable rental housing rights notice by address." }, { property: "og:type", content: "article" }, { name: "twitter:card", content: "summary" }] }), component: Notice });
function Notice() { const { address } = Route.useLoaderData(); const { date } = useAsOf(); const { t, lang } = useLang(); const result = resolveAddress(address, date, data); const city = result.stack.city || address.legal_city || address.postal_city; const why = city === "Boston" ? t.v2.notice.boston : city === "Cambridge" ? t.v2.notice.cambridge : t.v2.notice.other; return <article className="print-document mx-auto max-w-4xl p-6 pb-24"><div className="no-print flex justify-end"><Button onClick={() => window.print()}>{t.v2.notice.print}</Button></div><p className="eyebrow">Statute Street</p><h1 className="mt-2 text-4xl font-semibold">{t.v2.notice.title(address.street_address)}</h1><p className="mt-5 text-sm text-muted-foreground">{why}</p><p className="mt-5">{t.v2.notice.issuedBy}</p><p>{t.v2.notice.date}: {formatDate(date, lang)}</p>{groups.map((group) => { const items = group.c.flatMap((category) => result.byCategory[category]).filter((item) => item.badge === "applies"); return <section key={group.k} className="mt-8"><h2 className="border-b border-border pb-2 text-2xl font-semibold">{t.v2.notice.groups[group.k]}</h2>{items.length ? items.map((item) => <div key={item.rule.team_rule_id} className="py-4"><p>{lang === "es" ? item.rule.requirement_es || item.rule.requirement : item.rule.requirement}</p>{lang === "es" && !item.rule.requirement_es && <p className="text-xs text-status-review">{t.v2.notice.spanishPending}</p>}<p className="mt-1 font-mono text-xs">{item.rule.citation}</p></div>) : <p className="py-4 text-sm text-muted-foreground">{t.v2.notice.empty}</p>}</section>; })}<p className="mt-10 border-t border-border pt-4 text-sm">{t.banner}</p></article>; }