import { createFileRoute, notFound } from "@tanstack/react-router";
import { getAddress, data } from "@/data";
import { resolveAddress } from "@/lib/resolve";
import { useAsOf } from "@/components/WorkspaceShell";
import { Button } from "@/components/ui/button";
import { useLang } from "@/i18n";
import { formatDate } from "@/lib/format";
const groups=[{k:"rent",c:["rent_increase_limits"]},{k:"deposits",c:["security_deposits"]},{k:"ending",c:["just_cause_eviction"]},{k:"screening",c:["screening_restrictions","application_screening_fees"]}] as const;
export const Route=createFileRoute("/app/notice/")({loader:({params})=>{const address=getAddress(params.id);if(!address)throw notFound();return{address}},head:()=>({meta:[{title:"Statute Street: Tenant notice"},{name:"description",content:"A printable rental housing rights notice by address."},{property:"og:title",content:"Statute Street: Tenant notice"},{property:"og:description",content:"A printable rental housing rights notice by address."},{property:"og:type",content:"article"},{name:"twitter:card",content:"summary"}]}),component:Notice});
function Notice(){const {address}=Route.useLoaderData();const {date}=useAsOf();const {t,lang}=useLang();const r=resolveAddress(address,date,data);return <article className="print-document mx-auto max-w-4xl p-6 pb-24"><div className="no-print flex justify-end"><Button onClick={()=>window.print()}>{t.v2.notice.print}</Button></div><p className="eyebrow">Statute Street</p><h1 className="mt-2 text-4xl font-semibold">{t.v2.notice.title(address.street_address)}</h1><p className="mt-2 font-mono">{formatDate(date,lang)} · {r.stack.city}, {address.state}</p><p className="mt-5 text-sm text-muted-foreground">{t.v2.notice.why}</p>{groups.map(g=>{const items=g.c.flatMap(c=>r.byCategory[c]).filter(i=>i.badge==="applies");return <section key={g.k} className="mt-8"><h2 className="border-b border-border pb-2 text-2xl font-semibold">{t.v2.notice.groups[g.k]}</h2>{items.length?items.map(i=><div key={i.rule.team_rule_id} className="py-4"><p>{lang==="es"?(i.rule.requirement_es||i.rule.requirement):i.rule.requirement}</p>{lang==="es"&&!i.rule.requirement_es&&<p className="text-xs text-status-review">{t.v2.notice.spanishPending}</p>}<p className="mt-1 font-mono text-xs">{i.rule.citation}</p></div>):<p className="py-4 text-sm text-muted-foreground">{t.v2.notice.empty}</p>}</section>})}<p className="mt-10 border-t border-border pt-4 text-sm">{t.banner}</p></article>}
