import { useMemo, useState } from "react";
import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { getAddresses, data } from "@/data";
import { resolveAddress, normDate, BADGE_ORDER, type Badge } from "@/lib/resolve";
import { useAsOf } from "@/components/WorkspaceShell";
import { useLang } from "@/i18n";
import { StatusBadge } from "@/components/StatusBadge";
import { formatDate } from "@/lib/format";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/app/")({ head: () => ({ meta: [{ title: "Statute Street: Portfolio" }, { name: "description", content: "Dated rental housing determinations across the portfolio." }, { property: "og:title", content: "Statute Street: Portfolio" }, { property: "og:description", content: "Dated rental housing determinations across the portfolio." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Portfolio });

function Portfolio() {
  const { t, lang } = useLang(); const { date } = useAsOf(); const navigate = useNavigate(); const addresses = getAddresses();
  const [q, setQ] = useState(""); const [state, setState] = useState(""); const [city, setCity] = useState(""); const [status, setStatus] = useState(""); const [flagged, setFlagged] = useState(false); const [descending, setDescending] = useState(false);
  const rows = useMemo(() => addresses.map((address) => { const result = resolveAddress(address, date, data); const next = Object.values(result.byCategory).flat().map((item) => normDate(item.rule.effective_date)).filter((value): value is string => Boolean(value && value > date)).sort()[0] ?? ""; return { address, result, next }; }), [addresses, date]);
  const filtered = rows.filter(({ address, result }) => { const hay = `${address.address_id} ${address.street_address} ${address.postal_city} ${address.legal_city} ${address.zip}`.toLowerCase(); return (!q || hay.includes(q.toLowerCase())) && (!state || address.state === state) && (!city || (address.legal_city || address.postal_city) === city) && (!status || result.counts[status as Badge] > 0) && (!flagged || result.counts.review > 0); }).sort((a, b) => descending ? b.next.localeCompare(a.next) : a.next.localeCompare(b.next));
  const unknown = rows.filter(({ result }) => result.counts.unknown > 0).length; const flags = rows.filter(({ result }) => result.counts.review > 0).length; const applies = rows.reduce((total, { result }) => total + result.counts.applies, 0);
  return <div className="p-4 pb-24 lg:p-6"><header><p className="eyebrow">{formatDate(date, lang)}</p><h1 className="mt-1 text-4xl font-semibold">{t.v2.portfolio.title}</h1><p className="mt-2 text-muted-foreground">{t.v2.portfolio.lead}</p></header><div className="mt-6 grid grid-cols-2 border-y border-border lg:grid-cols-4">{[[t.v2.portfolio.summary.total, rows.length], [t.v2.portfolio.summary.unknown, unknown], [t.v2.portfolio.summary.flagged, flags], [t.v2.portfolio.summary.inForce, applies]].map(([label, number]) => <div key={String(label)} className="border-r border-border p-4 last:border-0"><p className="font-mono text-2xl font-semibold">{number}</p><p className="text-xs text-muted-foreground">{label}</p></div>)}</div>
    <div className="mt-5 flex flex-wrap gap-2"><input value={q} onChange={(event) => setQ(event.target.value)} placeholder={t.v2.portfolio.filters.search} className="h-9 min-w-60 flex-1 border border-input bg-background px-3 text-sm" /><select value={state} onChange={(event) => setState(event.target.value)} className="border border-input bg-background px-2 text-sm"><option value="">{t.v2.portfolio.filters.state}</option>{[...new Set(addresses.map((address) => address.state))].map((value) => <option key={value}>{value}</option>)}</select><select value={city} onChange={(event) => setCity(event.target.value)} className="border border-input bg-background px-2 text-sm"><option value="">{t.v2.portfolio.filters.city}</option>{[...new Set(addresses.map((address) => address.legal_city || address.postal_city))].sort().map((value) => <option key={value}>{value}</option>)}</select><select value={status} onChange={(event) => setStatus(event.target.value)} className="border border-input bg-background px-2 text-sm"><option value="">{t.v2.portfolio.filters.status}</option>{BADGE_ORDER.map((value) => <option key={value} value={value}>{t.badges[value]}</option>)}</select><label className="flex items-center gap-2 border border-input px-3 text-sm"><input type="checkbox" checked={flagged} onChange={(event) => setFlagged(event.target.checked)} />{t.v2.portfolio.filters.flagged}</label><Button variant="ghost" onClick={() => { setQ(""); setState(""); setCity(""); setStatus(""); setFlagged(false); }}>{t.v2.portfolio.filters.clear}</Button></div>
    <div className="mt-4 overflow-x-auto border border-border"><table className="w-full min-w-[1000px] text-left text-[13px]"><thead className="sticky top-0 bg-secondary"><tr><th className="px-3 py-2">{t.v2.portfolio.cols.address}</th><th className="px-3 py-2">{t.v2.portfolio.cols.jurisdiction}</th><th className="px-3 py-2">{t.v2.portfolio.cols.built}</th><th className="px-3 py-2">{t.v2.portfolio.cols.units}</th><th className="px-3 py-2">{t.v2.portfolio.cols.use}</th><th className="px-3 py-2">{t.v2.portfolio.cols.determinations}</th><th className="px-3 py-2">{t.v2.portfolio.cols.flags}</th><th className="px-3 py-2"><Button variant="ghost" size="sm" onClick={() => setDescending((value) => !value)}>{t.v2.portfolio.cols.change} {descending ? "↓" : "↑"}</Button></th></tr></thead><tbody>{filtered.map(({ address, result, next }) => <tr key={address.address_id} tabIndex={0} onClick={() => navigate({ to: "/app/address/$id", params: { id: address.address_id }, search: { asof: date } })} onKeyDown={(event) => event.key === "Enter" && navigate({ to: "/app/address/$id", params: { id: address.address_id }, search: { asof: date } })} className="cursor-pointer border-t border-border hover:bg-secondary"><td className="px-3 py-2 font-medium">{address.street_address}<span className="block font-mono text-xs text-muted-foreground">{address.address_id}</span></td><td className="px-3 py-2">{address.legal_city || result.stack.city}, {address.legal_state || address.state}</td><td className="px-3 py-2 font-mono">{address.year_built || t.address.notInRecords}</td><td className="px-3 py-2 font-mono">{address.units || t.address.notInRecords}</td><td className="px-3 py-2">{address.use_description || t.address.notInRecords}</td><td className="px-3 py-2"><div className="flex flex-wrap gap-1">{BADGE_ORDER.filter((badge) => badge !== "none" && result.counts[badge]).map((badge) => <span key={badge} className="inline-flex items-center gap-1"><StatusBadge kind={badge} className="px-1.5" /><b className="font-mono">{result.counts[badge]}</b></span>)}{result.counts.none > 0 && <span className="text-muted-foreground">{t.badges.none} {result.counts.none}</span>}</div></td><td className="px-3 py-2 font-mono">{result.counts.review || ""}</td><td className="px-3 py-2 font-mono">{next ? formatDate(next, lang) : ""}</td></tr>)}</tbody></table>{filtered.length === 0 && <p className="p-6 text-sm text-muted-foreground">{t.v2.portfolio.empty}</p>}</div></div>;
}