import { createFileRoute, notFound } from "@tanstack/react-router";
import { getAddress, data, getSources } from "@/data";
import { missingFacts, resolveAddress, type ResolvedItem } from "@/lib/resolve";
import { useAsOf } from "@/components/WorkspaceShell";
import { Button } from "@/components/ui/button";
import { useLang } from "@/i18n";
import { formatDate, formatTimestamp } from "@/lib/format";
import { appMeta } from "@/lib/meta";
export const Route = createFileRoute("/app/record/$id")({ validateSearch: (search: Record<string, unknown>) => ({ asof: typeof search["asof"] === "string" ? search["asof"] : undefined, action: typeof search["action"] === "string" ? search["action"] : undefined }), loader: ({ params }) => { const address = getAddress(params.id); if (!address) throw notFound(); return { address }; }, head: () => ({ meta: [{ title: "Statute Street: Reliance record" }, { name: "description", content: "A printable record of dated housing rule determinations." }, { property: "og:title", content: "Statute Street: Reliance record" }, { property: "og:description", content: "A printable record of dated housing rule determinations." }, { property: "og:type", content: "article" }, { name: "twitter:card", content: "summary" }] }), component: RecordPage });
function RecordPage() { const { address } = Route.useLoaderData(); const search = Route.useSearch(); const global = useAsOf(); const date = search.asof || global.date; const { t, lang } = useLang(); const result = resolveAddress(address, date, data); const items = Object.values(result.byCategory).flat().filter((item) => item.badge !== "failed"); const relied = items.filter((item) => item.badge === "applies"); const notApplicable = items.filter((item) => ["superseded", "not_yet_effective", "pending", "none"].includes(item.badge)); const unresolved = items.filter((item) => item.badge === "unknown"); const legal = `${result.stack.city || address.legal_city || address.postal_city}, ${address.legal_state || address.state}`; return <article className="print-document mx-auto max-w-4xl p-6 pb-24"><div className="no-print mb-6 flex justify-end"><Button onClick={() => window.print()}>{t.v2.record.print}</Button></div><h1 className="text-4xl font-semibold">{t.v2.record.title}</h1><dl className="mt-6 grid gap-3 border-y border-border py-4 font-mono text-sm sm:grid-cols-2"><Field label={t.v2.check.address} value={address.street_address} /><Field label={t.v2.determination.legalJurisdiction} value={legal} /><Field label={t.v2.determination.recordId} value={address.address_id} /><Field label={t.v2.determination.asOf} value={formatDate(date, lang)} /><Field label={t.v2.record.action} value={search.action || t.v2.record.allActions} /><Field label={t.v2.record.generated} value={formatTimestamp(new Date().toISOString(), lang)} /><Field label={t.v2.record.rulesEngine} value={`${appMeta?.rules_version || t.v2.changes.unavailable} · ${appMeta?.engine_commit || t.v2.changes.unavailable}`} /></dl><RecordSection title={t.v2.record.relied} items={relied} address={address} /><RecordSection title={t.v2.record.notApplicable} items={notApplicable} address={address} /><RecordSection title={t.v2.record.unresolved} items={unresolved} address={address} /><p className="mt-10 border-t border-border pt-4 text-sm">{t.banner}</p><p className="mt-10">{t.v2.record.reviewedBy}: ______________________________</p><p className="no-print mt-6 text-xs text-muted-foreground">{t.v2.record.notStored}</p></article>; }
function Field({ label, value }: { label: string; value: string }) { return <div><dt className="text-muted-foreground">{label}</dt><dd>{value}</dd></div>; }
function RecordSection({ title, items, address }: { title: string; items: ResolvedItem[]; address: ReturnType<typeof getAddress> extends infer T ? Exclude<T, undefined> : never }) { const { t, lang } = useLang(); return <section className="mt-8"><h2 className="text-2xl font-semibold">{title}</h2>{items.length === 0 ? <p className="mt-3 text-sm text-muted-foreground">{t.v2.record.none}</p> : items.map((item) => { const source = getSources().find((entry) => entry.source_id === item.rule.source_doc_id); const governing = item.governedBy ? data.rulesById.get(item.governedBy) : undefined; return <section key={item.rule.team_rule_id} className="mt-5 border-t border-border pt-4"><h3 className="text-xl font-semibold">{item.rule.title}</h3>{item.explanation && <p className="mt-2">{item.explanation}</p>}{item.badge === "unknown" && <p className="mt-2">{t.v2.determination.needs(missingFacts(address).map((fact) => t.address.missing[fact]).join(", "))}</p>}{item.badge === "not_yet_effective" && item.rule.effective_date && <p className="mt-2">{t.address.takesEffect(formatDate(item.rule.effective_date, lang))}</p>}{governing && <p className="mt-2">{t.v2.determination.governedBy(governing.title)}</p>}<p className="mt-2">{item.rule.requirement}</p><blockquote className="quote-block mt-3">{item.rule.quoted_span}</blockquote><p className="mt-2 font-mono text-xs">{item.rule.citation} · {item.rule.source_url}</p><p className="font-mono text-xs">{source?.retrieved_at ? formatTimestamp(source.retrieved_at, lang) : t.address.retrievalMissing}</p></section>; })}</section>; }