import { useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Check, Copy, ExternalLink } from "lucide-react";
import { getDataIssues,getRulesCitingSource,getSources } from "@/data";
import { fingerprint,formatTimestamp } from "@/lib/format";
import { useLang } from "@/i18n";
import { Button } from "@/components/ui/button";
export const Route=createFileRoute("/app/evidence")({head:()=>({meta:[{title:"Statute Street: Evidence register"},{name:"description",content:"Source documents, citations, retrieval dates, and fingerprints."},{property:"og:title",content:"Statute Street: Evidence register"},{property:"og:description",content:"Source documents, citations, retrieval dates, and fingerprints."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Evidence});
function Evidence(){const {t,lang}=useLang();const [q,setQ]=useState("");const [copied,setCopied]=useState("");const sources=getSources();const rows=useMemo(()=>sources.filter(s=>!q||`${s.source_id} ${s.title} ${s.jurisdiction} ${s.citation}`.toLowerCase().includes(q.toLowerCase())),[sources,q]);return <div className="p-4 pb-24 lg:p-6"><h1 className="text-4xl font-semibold">{t.v2.evidence.title}</h1><p className="mt-2 text-muted-foreground">{t.v2.evidence.lead}</p><input type="search" value={q} onChange={e=>setQ(e.target.value)} placeholder={t.audit.searchPlaceholder} className="mt-6 w-full max-w-md border border-input bg-background px-3 py-2"/><div className="mt-4 overflow-x-auto border border-border"><table className="w-full min-w-[950px] text-left text-[13px]"><thead className="sticky top-0 bg-secondary"><tr>{[t.audit.cols.id,t.audit.cols.title,t.audit.cols.jurisdiction,t.address.citation,t.audit.cols.retrieved,t.audit.cols.sha,t.v2.evidence.basis,t.v2.evidence.rules].map(x=><th key={x} className="px-3 py-2">{x}</th>)}</tr></thead><tbody>{rows.map(s=><tr key={s.source_id} className="border-t border-border hover:bg-secondary"><td className="px-3 py-2 font-mono">{s.source_id}</td><td className="px-3 py-2">{s.url?<a href={s.url} target="_blank" rel="noreferrer" className="text-primary underline">{s.title}<ExternalLink className="ml-1 inline h-3 w-3"/></a>:s.title}</td><td className="px-3 py-2">{s.jurisdiction}</td><td className="px-3 py-2 font-mono text-xs">{s.citation}</td><td className="px-3 py-2 font-mono">{s.retrieved_at?formatTimestamp(s.retrieved_at,lang):t.address.retrievalMissing}</td><td className="px-3 py-2"><span title={s.sha256||""} className="font-mono">{fingerprint(s.sha256)}</span>{s.sha256&&<Button variant="ghost" size="icon" onClick={()=>{void navigator.clipboard.writeText(s.sha256||"");setCopied(s.source_id)}} aria-label={t.audit.copy}>{copied===s.source_id?<Check/>:<Copy/>}</Button>}</td><td className="px-3 py-2">{t.v2.determination.primary}</td><td className="px-3 py-2 font-mono">{getRulesCitingSource(s).length}</td></tr>)}</tbody></table>{rows.length===0&&<p className="p-5 text-sm text-muted-foreground">{t.audit.empty}</p>}</div><section className="mt-10"><h2 className="text-2xl font-semibold">{t.audit.issuesTitle}</h2><p className="mt-2 font-mono text-sm">{t.v2.evidence.skipped(getDataIssues().length)}</p>{getDataIssues().map((i,k)=><p key={k} className="mt-2 border-t border-border pt-2 text-sm">{i.file} · {i.record}: {i.message}</p>)}</section></div>}
