import { useEffect, useMemo, useRef, useState } from "react";
import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { getAddress, data } from "@/data";
import { resolveAddress, BADGE_ORDER, missingFacts, type Badge, type ResolvedItem } from "@/lib/resolve";
import { useAsOf } from "@/components/WorkspaceShell";
import { DeterminationRow } from "@/components/DeterminationRow";
import { StatusBadge } from "@/components/StatusBadge";
import { RequestAccessModal } from "@/components/RequestAccessModal";
import { Button, buttonVariants } from "@/components/ui/button";
import { useLang } from "@/i18n";
import { formatDate } from "@/lib/format";

const groups = [{ k: "rent", cats: ["rent_increase_limits"] }, { k: "software", cats: ["algorithmic_rent_setting"] }, { k: "screening", cats: ["screening_restrictions", "application_screening_fees"] }, { k: "deposits", cats: ["security_deposits"] }, { k: "ending", cats: ["just_cause_eviction"] }] as const;
export const Route = createFileRoute("/app/address/$id")({ loader: ({ params }) => { const address = getAddress(params.id); if (!address) throw notFound(); return { address }; }, head: ({ loaderData }) => { const title = loaderData ? `Statute Street: ${loaderData.address.street_address}` : "Statute Street: Address not found"; return { meta: [{ title }, { name: "description", content: "A dated rental housing compliance determination with quoted evidence." }, { property: "og:title", content: title }, { property: "og:description", content: "A dated rental housing compliance determination with quoted evidence." }, { property: "og:type", content: "article" }, { name: "twitter:card", content: "summary" }] }; }, component: AddressRecord, notFoundComponent: NotFound });
function NotFound() { const { t } = useLang(); return <div className="p-8"><h1 className="text-3xl font-semibold">{t.address.notFoundTitle}</h1><p className="mt-2">{t.address.notFoundBody}</p><Link to="/app" search={{ asof: "2026-10-01" }} className={buttonVariants({ className: "mt-5" })}>{t.address.back}</Link></div>; }

function AddressRecord() {
  const { address } = Route.useLoaderData(); const { t, lang } = useLang(); const { date } = useAsOf();
  const result = useMemo(() => resolveAddress(address, date, data), [address, date]);
  const [filter, setFilter] = useState<Badge | "review" | null>(null); const [access, setAccess] = useState(false); const previous = useRef<Record<string, Badge>>({}); const [changed, setChanged] = useState<Set<string>>(new Set());
  useEffect(() => { const next = Object.fromEntries(Object.values(result.byCategory).flat().map((item) => [item.rule.team_rule_id, item.badge])); const ids = Object.keys(next).filter((id) => previous.current[id] && previous.current[id] !== next[id]); previous.current = next; if (ids.length) { setChanged(new Set(ids)); const timer = setTimeout(() => setChanged(new Set()), 3000); return () => clearTimeout(timer); } return undefined; }, [result]);
  const all = Object.values(result.byCategory).flat(); const legal = result.stack.city || address.legal_city || address.postal_city;
  const obligations = all.filter((item) => item.badge === "applies");
  const upcoming = all.filter((item) => item.badge === "not_yet_effective"); const unknown = all.filter((item) => item.badge === "unknown"); const pending = all.filter((item) => item.badge === "pending");
  const facts = [[t.v2.determination.legalJurisdiction, `${legal || t.address.notInRecords}, ${address.legal_state || address.state}`], [t.address.yearBuilt, address.year_built || t.address.notInRecords], [t.address.units, address.units || t.address.notInRecords], [t.v2.determination.use, address.use_description || t.address.notInRecords], ...(address.postal_city && address.postal_city !== legal ? [[t.v2.determination.mailingCity, address.postal_city]] : [])];
  return <div className="p-4 pb-24 lg:p-6"><header className="border-b border-border pb-5"><p className="eyebrow">{t.v2.determination.title}</p><div className="mt-2 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-4xl font-semibold">{address.street_address}</h1><p className="mt-1">{legal}, {address.state} {address.zip}</p></div><div className="font-mono text-xs text-muted-foreground"><p>{t.v2.determination.asOf}: {formatDate(date, lang)}</p><p>{t.v2.determination.recordId} {address.address_id}</p></div></div><dl className="mt-5 grid gap-px bg-border sm:grid-cols-2 xl:grid-cols-5">{facts.map(([label, value]) => <div key={label} className="bg-background p-3"><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1 text-sm font-medium">{value}</dd></div>)}</dl><div className="mt-5 flex flex-wrap gap-2"><Link to="/app/check" search={{ asof: date, address: address.address_id }} className={buttonVariants()}>{t.v2.determination.checkAction}</Link><Link to="/app/record/$id" params={{ id: address.address_id }} search={{ asof: date, action: undefined }} className={buttonVariants({ variant: "outline" })}>{t.v2.determination.recordReliance}</Link><Link to="/app/notice/$id" params={{ id: address.address_id }} search={{ asof: date }} className={buttonVariants({ variant: "outline" })}>{t.v2.determination.tenantNotice}</Link></div></header>
    <div className="mt-6 grid gap-5 lg:grid-cols-2"><LeadPanel title={t.v2.determination.keyObligations}>{groups.map((group) => { const items = obligations.filter((item) => group.cats.includes(item.rule.category as never)); return items.length ? <section key={group.k}><h3 className="eyebrow mt-4 first:mt-0">{t.v2.determination.actions[group.k]}</h3>{items.map((item) => <KeyLine key={item.rule.team_rule_id} item={item} />)}</section> : null; })}</LeadPanel><LeadPanel title={t.v2.determination.comingUnresolved}>{upcoming.map((item) => <p key={item.rule.team_rule_id}>{item.rule.title}, {t.v2.determination.from(formatDate(item.rule.effective_date, lang))}</p>)}{unknown.flatMap((item) => missingFacts(address).map((fact) => <p key={`${item.rule.team_rule_id}-${fact}`}>{t.v2.determination.needs(t.address.missing[fact])}</p>))}{pending.map((item) => <p key={item.rule.team_rule_id}>{item.rule.title} · {t.v2.determination.billNotLaw}</p>)}{upcoming.length + unknown.length + pending.length === 0 && <p className="text-muted-foreground">{t.v2.determination.nothingUpcoming}</p>}</LeadPanel></div>
    <section className="mt-6 flex flex-wrap gap-2 border-b border-border py-4">{[...BADGE_ORDER, "review" as const].map((badge) => <Button key={badge} variant="ghost" size="sm" onClick={() => setFilter(filter === badge ? null : badge)} aria-pressed={filter === badge}><StatusBadge kind={badge} /><b className="font-mono text-sm">{result.counts[badge]}</b></Button>)}</section>{!result.hasLookups && <p className="mt-5 border border-status-unknown/40 bg-status-unknown-tint p-3 text-sm">{t.address.noLookups}</p>}
    <div className="mt-6 grid gap-8 xl:grid-cols-[minmax(0,1fr)_280px]"><div>{groups.map((group) => { const items = group.cats.flatMap((category) => result.byCategory[category]).filter((item) => !filter || filter === "review" ? (!filter || item.review) : item.badge === filter).sort((a, b) => Number(a.badge === "none") - Number(b.badge === "none")); return <section key={group.k} className="mb-8"><div className="flex items-baseline justify-between border-b-2 border-foreground pb-2"><h2 className="text-2xl font-semibold">{t.v2.determination.actions[group.k]}</h2><span className="font-mono">{items.length}</span></div>{items.length ? items.map((item) => <DeterminationRow key={item.rule.team_rule_id} item={item} address={address} changed={changed.has(item.rule.team_rule_id)} />) : <p className="py-4 text-sm text-muted-foreground">{t.v2.determination.noRows}</p>}</section>; })}</div><aside className="self-start border-t border-border pt-5 xl:sticky xl:top-24"><h2 className="text-xl font-semibold">{t.v2.determination.monitor}</h2><p className="mt-2 text-sm text-muted-foreground">{t.v2.determination.monitorBody}</p><Button className="mt-4" onClick={() => setAccess(true)}>{t.v2.requestAccess}</Button></aside></div><RequestAccessModal open={access} onClose={() => setAccess(false)} subject={address.street_address} /></div>;
}
function LeadPanel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="border-t-2 border-foreground pt-4"><h2 className="text-xl font-semibold">{title}</h2><div className="mt-3 space-y-2 text-sm">{children}</div></section>; }
function KeyLine({ item }: { item: ResolvedItem }) { const { t } = useLang(); const unless = Boolean(item.explanation?.toLowerCase().startsWith("applies unless")); return <div className="border-t border-border py-2"><StatusBadge kind="applies" outline={unless} /><p className="mt-1 font-mono font-semibold" lang="en">{item.rule.key_value || item.rule.title}</p>{item.rule.key_value && <p className="text-xs text-muted-foreground" lang="en">{item.rule.title}</p>}<span className="sr-only">{unless ? t.v2.determination.appliesUnless : t.badges.applies}</span></div>; }