import { useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { getAddress, getChanges } from "@/data";
import registerRaw from "@/data/change_register.json";
import { formatDate, parseDisplayDate } from "@/lib/format";
import { StatusBadge } from "@/components/StatusBadge";
import { RequestAccessModal } from "@/components/RequestAccessModal";
import { Button } from "@/components/ui/button";
import { useAsOf } from "@/components/WorkspaceShell";
import { useLang } from "@/i18n";
export const Route = createFileRoute("/app/changes")({ head: () => ({ meta: [{ title: "Statute Street: Change register" }, { name: "description", content: "Legal changes and their tested address impact." }, { property: "og:title", content: "Statute Street: Change register" }, { property: "og:description", content: "Legal changes and their tested address impact." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Changes });
function Changes() { const { t, lang } = useLang(); const { date } = useAsOf(); const [watch, setWatch] = useState(""); const legacy = new Map(getChanges().map((change) => [change.test_id, change])); const rows = registerRaw.changes.length ? registerRaw.changes : getChanges().map((change) => ({ test_id: change.test_id, title: change.test_id, instrument: "", jurisdiction: "", enacted: "", effective: "", status: "in_force" as const, summary: change.notes, addresses_affected: change.affected_address_ids.length, review_needed: change.conflict_flag_address_ids.length })); return <div className="p-4 pb-24 lg:p-6"><h1 className="text-4xl font-semibold">{t.v2.changes.title}</h1><p className="mt-2 text-muted-foreground">{t.v2.changes.lead}</p><div className="mt-6 overflow-x-auto border border-border"><table className="w-full min-w-[1180px] text-left text-[13px]"><thead className="bg-secondary"><tr>{Object.values(t.v2.changes.cols).map((label) => <th key={label} className="px-3 py-2">{label}</th>)}</tr></thead><tbody>{rows.map((change) => { const affected = legacy.get(change.test_id)?.affected_address_ids ?? []; const first = getAddress(affected[0] ?? ""); const enacted = parseDisplayDate(change.enacted); const effective = parseDisplayDate(change.effective); const status = change.status === "in_force" ? "applies" : change.status as "not_yet_effective" | "pending" | "failed"; return <tr key={change.test_id} className="border-t border-border align-top hover:bg-secondary"><td className="px-3 py-3"><p className="font-serif text-base font-semibold">{change.title}</p><p className="mt-1 font-mono text-xs">{change.instrument}</p></td><td className="px-3 py-3">{change.jurisdiction}</td><td className="px-3 py-3">{enacted ? formatDate(enacted, lang) : change.enacted}</td><td className="px-3 py-3">{effective ? formatDate(effective, lang) : change.effective}</td><td className="px-3 py-3"><StatusBadge kind={status} /></td><td className="max-w-lg px-3 py-3">{change.summary}</td><td className="px-3 py-3 font-mono">{change.addresses_affected}</td><td className="px-3 py-3 font-mono">{change.review_needed}</td><td className="px-3 py-3"><div className="flex gap-2">{first && <Link to="/app/address/$id" params={{ id: first.address_id }} search={{ asof: date }} className="text-primary underline">{t.v2.changes.example}</Link>}<Button variant="link" className="h-auto p-0" onClick={() => setWatch(change.test_id)}>{t.v2.changes.watch}</Button></div></td></tr>; })}</tbody></table></div><RequestAccessModal open={Boolean(watch)} onClose={() => setWatch("")} subject={watch} /></div>; }