import { ExternalLink } from "lucide-react";
import type { Address } from "@/data";
import { getSourceByUrl, getSources } from "@/data";
import type { ResolvedItem } from "@/lib/resolve";
import { confidenceLabel, missingFacts } from "@/lib/resolve";
import { fingerprint, formatTimestamp, hideInternalNote } from "@/lib/format";
import { useLang } from "@/i18n";
import { StatusBadge } from "./StatusBadge";

export function DeterminationRow({ item, address, changed=false }: { item: ResolvedItem; address: Address; changed?: boolean }) {
 const {t,lang}=useLang(); const r=item.rule; const source=getSourceByUrl(r.source_url) ?? getSources().find(s=>s.source_id===r.source_doc_id); const explanation=hideInternalNote(item.explanation); const review=hideInternalNote(item.reviewNote) ?? (item.review?t.address.reviewHidden:null); const appliesUnless=item.badge==="applies" && Boolean(explanation?.toLowerCase().startsWith("applies unless"));
 return <details id={`rule-${r.team_rule_id}`} className={`group border-b border-border ${changed?"status-pulse":""}`}><summary className="grid cursor-pointer list-none gap-2 px-3 py-3 hover:bg-secondary sm:grid-cols-[auto_minmax(0,1fr)_auto] sm:items-start"><div className="flex flex-wrap gap-1"><StatusBadge kind={item.badge} outline={appliesUnless}/>{item.review&&<StatusBadge kind="review" className="px-1.5 text-xs"/>}{changed&&<span className="text-xs font-semibold text-primary">{t.v2.determination.changed}</span>}</div><div><h3 className="font-semibold" lang="en">{r.title}</h3>{explanation&&<p className="mt-0.5 text-sm text-muted-foreground" lang="en">{explanation}</p>} {item.badge==="unknown"&&<div className="mt-1 flex gap-1">{missingFacts(address).map(m=><span key={m} className="border border-status-unknown/40 px-1.5 text-xs">{t.address.missing[m]}</span>)}</div>}</div><div className="text-left sm:text-right"><p className="font-mono text-xs text-muted-foreground">{t.v2.determination.level(t.address.level[r.level],r.jurisdiction)}</p>{r.key_value&&<p className="mt-1 max-w-xs font-mono text-sm font-semibold" lang="en">{r.key_value}</p>}</div></summary><div className="grid gap-5 bg-card px-3 pb-5 pt-2 text-sm md:grid-cols-2"><div><p className="eyebrow">{t.v2.determination.requirement}</p><p className="mt-2" lang="en">{r.requirement}</p>{item.review&&review&&<p className="mt-3 border-l-2 border-status-review pl-3">{review}</p>}</div><div><p className="eyebrow">{t.address.evidence}</p>{r.quoted_span?<blockquote className="quote-block mt-2" lang="en">“{r.quoted_span}”</blockquote>:<p className="mt-2 text-muted-foreground">{t.address.quoteMissing}</p>}<p className="mt-2 font-mono text-xs" lang="en">{r.citation}</p>{r.source_url&&<a className="mt-2 inline-flex items-center gap-1 text-primary underline" href={r.source_url} target="_blank" rel="noreferrer">{t.address.openSource}<ExternalLink className="h-3 w-3"/></a>}<div className="mt-2 font-mono text-xs text-muted-foreground">{source?.retrieved_at?t.address.retrieved(formatTimestamp(source.retrieved_at,lang)):t.address.retrievalMissing}{source?.sha256?` · ${fingerprint(source.sha256)}`:""}</div><p className="mt-1 text-xs">{t.address.confidence[confidenceLabel(r.confidence).level](confidenceLabel(r.confidence).value)} · {r.confidence>=.8?t.v2.determination.lawyer:t.v2.determination.machine}</p></div></div></details>;
}
