/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AddressRouteImport } from './routes/address.'
import { Route as AddressIdRouteImport } from './routes/address.$id'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppChangesRouteImport } from './routes/app.changes'
import { Route as AppCheckRouteImport } from './routes/app.check'
import { Route as AppEvidenceRouteImport } from './routes/app.evidence'
import { Route as AppMethodRouteImport } from './routes/app.method'
import { Route as AppReviewRouteImport } from './routes/app.review'
import { Route as AppAddressRouteImport } from './routes/app.address.'
import { Route as AppNoticeRouteImport } from './routes/app.notice.'
import { Route as AppRecordRouteImport } from './routes/app.record.'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressRoute = AddressRouteImport.update({
  id: '/address/',
  path: '/address/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressIdRoute = AddressIdRouteImport.update({
  id: '/address/$id',
  path: '/address/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppChangesRoute = AppChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckRoute = AppCheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => AppRoute,
} as any)
const AppEvidenceRoute = AppEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => AppRoute,
} as any)
const AppMethodRoute = AppMethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppAddressRoute = AppAddressRouteImport.update({
  id: '/address/',
  path: '/address/',
  getParentRoute: () => AppRoute,
} as any)
const AppNoticeRoute = AppNoticeRouteImport.update({
  id: '/notice/',
  path: '/notice/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordRoute = AppRecordRouteImport.update({
  id: '/record/',
  path: '/record/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/audit': typeof AuditRoute
  '/address/': typeof AddressRoute
  '/address/$id': typeof AddressIdRoute
  '/app/changes': typeof AppChangesRoute
  '/app/check': typeof AppCheckRoute
  '/app/evidence': typeof AppEvidenceRoute
  '/app/method': typeof AppMethodRoute
  '/app/review': typeof AppReviewRoute
  '/app/': typeof AppIndexRoute
  '/app/address/': typeof AppAddressRoute
  '/app/notice/': typeof AppNoticeRoute
  '/app/record/': typeof AppRecordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/address': typeof AddressRoute
  '/address/$id': typeof AddressIdRoute
  '/app/changes': typeof AppChangesRoute
  '/app/check': typeof AppCheckRoute
  '/app/evidence': typeof AppEvidenceRoute
  '/app/method': typeof AppMethodRoute
  '/app/review': typeof AppReviewRoute
  '/app': typeof AppIndexRoute
  '/app/address': typeof AppAddressRoute
  '/app/notice': typeof AppNoticeRoute
  '/app/record': typeof AppRecordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/audit': typeof AuditRoute
  '/address/': typeof AddressRoute
  '/address/$id': typeof AddressIdRoute
  '/app/changes': typeof AppChangesRoute
  '/app/check': typeof AppCheckRoute
  '/app/evidence': typeof AppEvidenceRoute
  '/app/method': typeof AppMethodRoute
  '/app/review': typeof AppReviewRoute
  '/app/': typeof AppIndexRoute
  '/app/address/': typeof AppAddressRoute
  '/app/notice/': typeof AppNoticeRoute
  '/app/record/': typeof AppRecordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/audit'
    | '/address/'
    | '/address/$id'
    | '/app/changes'
    | '/app/check'
    | '/app/evidence'
    | '/app/method'
    | '/app/review'
    | '/app/'
    | '/app/address/'
    | '/app/notice/'
    | '/app/record/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/audit'
    | '/address'
    | '/address/$id'
    | '/app/changes'
    | '/app/check'
    | '/app/evidence'
    | '/app/method'
    | '/app/review'
    | '/app'
    | '/app/address'
    | '/app/notice'
    | '/app/record'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/audit'
    | '/address/'
    | '/address/$id'
    | '/app/changes'
    | '/app/check'
    | '/app/evidence'
    | '/app/method'
    | '/app/review'
    | '/app/'
    | '/app/address/'
    | '/app/notice/'
    | '/app/record/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  AuditRoute: typeof AuditRoute
  AddressRoute: typeof AddressRoute
  AddressIdRoute: typeof AddressIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/address/': {
      id: '/address/'
      path: '/address'
      fullPath: '/address/'
      preLoaderRoute: typeof AddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/address/$id': {
      id: '/address/$id'
      path: '/address/$id'
      fullPath: '/address/$id'
      preLoaderRoute: typeof AddressIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/changes': {
      id: '/app/changes'
      path: '/changes'
      fullPath: '/app/changes'
      preLoaderRoute: typeof AppChangesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/check': {
      id: '/app/check'
      path: '/check'
      fullPath: '/app/check'
      preLoaderRoute: typeof AppCheckRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/evidence': {
      id: '/app/evidence'
      path: '/evidence'
      fullPath: '/app/evidence'
      preLoaderRoute: typeof AppEvidenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/method': {
      id: '/app/method'
      path: '/method'
      fullPath: '/app/method'
      preLoaderRoute: typeof AppMethodRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/review': {
      id: '/app/review'
      path: '/review'
      fullPath: '/app/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/address/': {
      id: '/app/address/'
      path: '/address'
      fullPath: '/app/address/'
      preLoaderRoute: typeof AppAddressRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notice/': {
      id: '/app/notice/'
      path: '/notice'
      fullPath: '/app/notice/'
      preLoaderRoute: typeof AppNoticeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/record/': {
      id: '/app/record/'
      path: '/record'
      fullPath: '/app/record/'
      preLoaderRoute: typeof AppRecordRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChangesRoute: typeof AppChangesRoute
  AppCheckRoute: typeof AppCheckRoute
  AppEvidenceRoute: typeof AppEvidenceRoute
  AppMethodRoute: typeof AppMethodRoute
  AppReviewRoute: typeof AppReviewRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAddressRoute: typeof AppAddressRoute
  AppNoticeRoute: typeof AppNoticeRoute
  AppRecordRoute: typeof AppRecordRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChangesRoute: AppChangesRoute,
  AppCheckRoute: AppCheckRoute,
  AppEvidenceRoute: AppEvidenceRoute,
  AppMethodRoute: AppMethodRoute,
  AppReviewRoute: AppReviewRoute,
  AppIndexRoute: AppIndexRoute,
  AppAddressRoute: AppAddressRoute,
  AppNoticeRoute: AppNoticeRoute,
  AppRecordRoute: AppRecordRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  AuditRoute: AuditRoute,
  AddressRoute: AddressRoute,
  AddressIdRoute: AddressIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
