/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AddressRouteImport } from './routes/address.'
import { Route as AddressIdRouteImport } from './routes/address.$id'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAddressRouteImport } from './routes/app.address.'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressRoute = AddressRouteImport.update({
  id: '/address/',
  path: '/address/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressIdRoute = AddressIdRouteImport.update({
  id: '/address/$id',
  path: '/address/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAddressRoute = AppAddressRouteImport.update({
  id: '/address/',
  path: '/address/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/audit': typeof AuditRoute
  '/address/': typeof AddressRoute
  '/address/$id': typeof AddressIdRoute
  '/app/': typeof AppIndexRoute
  '/app/address/': typeof AppAddressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/address': typeof AddressRoute
  '/address/$id': typeof AddressIdRoute
  '/app': typeof AppIndexRoute
  '/app/address': typeof AppAddressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/audit': typeof AuditRoute
  '/address/': typeof AddressRoute
  '/address/$id': typeof AddressIdRoute
  '/app/': typeof AppIndexRoute
  '/app/address/': typeof AppAddressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/audit'
    | '/address/'
    | '/address/$id'
    | '/app/'
    | '/app/address/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/audit'
    | '/address'
    | '/address/$id'
    | '/app'
    | '/app/address'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/audit'
    | '/address/'
    | '/address/$id'
    | '/app/'
    | '/app/address/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  AuditRoute: typeof AuditRoute
  AddressRoute: typeof AddressRoute
  AddressIdRoute: typeof AddressIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/address/': {
      id: '/address/'
      path: '/address'
      fullPath: '/address/'
      preLoaderRoute: typeof AddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/address/$id': {
      id: '/address/$id'
      path: '/address/$id'
      fullPath: '/address/$id'
      preLoaderRoute: typeof AddressIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/address/': {
      id: '/app/address/'
      path: '/address'
      fullPath: '/app/address/'
      preLoaderRoute: typeof AppAddressRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAddressRoute: typeof AppAddressRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAddressRoute: AppAddressRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  AuditRoute: AuditRoute,
  AddressRoute: AddressRoute,
  AddressIdRoute: AddressIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
