/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AddressIdRouteImport } from './routes/address.$id'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppChangesRouteImport } from './routes/app.changes'
import { Route as AppCheckRouteImport } from './routes/app.check'
import { Route as AppEvidenceRouteImport } from './routes/app.evidence'
import { Route as AppMethodRouteImport } from './routes/app.method'
import { Route as AppReviewRouteImport } from './routes/app.review'
import { Route as AppAddressIdRouteImport } from './routes/app.address.$id'
import { Route as AppNoticeIdRouteImport } from './routes/app.notice.$id'
import { Route as AppRecordIdRouteImport } from './routes/app.record.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressIdRoute = AddressIdRouteImport.update({
  id: '/address/$id',
  path: '/address/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppChangesRoute = AppChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckRoute = AppCheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => AppRoute,
} as any)
const AppEvidenceRoute = AppEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => AppRoute,
} as any)
const AppMethodRoute = AppMethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppAddressIdRoute = AppAddressIdRouteImport.update({
  id: '/address/$id',
  path: '/address/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppNoticeIdRoute = AppNoticeIdRouteImport.update({
  id: '/notice/$id',
  path: '/notice/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordIdRoute = AppRecordIdRouteImport.update({
  id: '/record/$id',
  path: '/record/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/audit': typeof AuditRoute
  '/address/$id': typeof AddressIdRoute
  '/app/changes': typeof AppChangesRoute
  '/app/check': typeof AppCheckRoute
  '/app/evidence': typeof AppEvidenceRoute
  '/app/method': typeof AppMethodRoute
  '/app/review': typeof AppReviewRoute
  '/app/': typeof AppIndexRoute
  '/app/address/$id': typeof AppAddressIdRoute
  '/app/notice/$id': typeof AppNoticeIdRoute
  '/app/record/$id': typeof AppRecordIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/address/$id': typeof AddressIdRoute
  '/app/changes': typeof AppChangesRoute
  '/app/check': typeof AppCheckRoute
  '/app/evidence': typeof AppEvidenceRoute
  '/app/method': typeof AppMethodRoute
  '/app/review': typeof AppReviewRoute
  '/app': typeof AppIndexRoute
  '/app/address/$id': typeof AppAddressIdRoute
  '/app/notice/$id': typeof AppNoticeIdRoute
  '/app/record/$id': typeof AppRecordIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/audit': typeof AuditRoute
  '/address/$id': typeof AddressIdRoute
  '/app/changes': typeof AppChangesRoute
  '/app/check': typeof AppCheckRoute
  '/app/evidence': typeof AppEvidenceRoute
  '/app/method': typeof AppMethodRoute
  '/app/review': typeof AppReviewRoute
  '/app/': typeof AppIndexRoute
  '/app/address/$id': typeof AppAddressIdRoute
  '/app/notice/$id': typeof AppNoticeIdRoute
  '/app/record/$id': typeof AppRecordIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/audit'
    | '/address/$id'
    | '/app/changes'
    | '/app/check'
    | '/app/evidence'
    | '/app/method'
    | '/app/review'
    | '/app/'
    | '/app/address/$id'
    | '/app/notice/$id'
    | '/app/record/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/audit'
    | '/address/$id'
    | '/app/changes'
    | '/app/check'
    | '/app/evidence'
    | '/app/method'
    | '/app/review'
    | '/app'
    | '/app/address/$id'
    | '/app/notice/$id'
    | '/app/record/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/audit'
    | '/address/$id'
    | '/app/changes'
    | '/app/check'
    | '/app/evidence'
    | '/app/method'
    | '/app/review'
    | '/app/'
    | '/app/address/$id'
    | '/app/notice/$id'
    | '/app/record/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  AuditRoute: typeof AuditRoute
  AddressIdRoute: typeof AddressIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/address/$id': {
      id: '/address/$id'
      path: '/address/$id'
      fullPath: '/address/$id'
      preLoaderRoute: typeof AddressIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/changes': {
      id: '/app/changes'
      path: '/changes'
      fullPath: '/app/changes'
      preLoaderRoute: typeof AppChangesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/check': {
      id: '/app/check'
      path: '/check'
      fullPath: '/app/check'
      preLoaderRoute: typeof AppCheckRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/evidence': {
      id: '/app/evidence'
      path: '/evidence'
      fullPath: '/app/evidence'
      preLoaderRoute: typeof AppEvidenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/method': {
      id: '/app/method'
      path: '/method'
      fullPath: '/app/method'
      preLoaderRoute: typeof AppMethodRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/review': {
      id: '/app/review'
      path: '/review'
      fullPath: '/app/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/address/$id': {
      id: '/app/address/$id'
      path: '/address/$id'
      fullPath: '/app/address/$id'
      preLoaderRoute: typeof AppAddressIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notice/$id': {
      id: '/app/notice/$id'
      path: '/notice/$id'
      fullPath: '/app/notice/$id'
      preLoaderRoute: typeof AppNoticeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/record/$id': {
      id: '/app/record/$id'
      path: '/record/$id'
      fullPath: '/app/record/$id'
      preLoaderRoute: typeof AppRecordIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChangesRoute: typeof AppChangesRoute
  AppCheckRoute: typeof AppCheckRoute
  AppEvidenceRoute: typeof AppEvidenceRoute
  AppMethodRoute: typeof AppMethodRoute
  AppReviewRoute: typeof AppReviewRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAddressIdRoute: typeof AppAddressIdRoute
  AppNoticeIdRoute: typeof AppNoticeIdRoute
  AppRecordIdRoute: typeof AppRecordIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChangesRoute: AppChangesRoute,
  AppCheckRoute: AppCheckRoute,
  AppEvidenceRoute: AppEvidenceRoute,
  AppMethodRoute: AppMethodRoute,
  AppReviewRoute: AppReviewRoute,
  AppIndexRoute: AppIndexRoute,
  AppAddressIdRoute: AppAddressIdRoute,
  AppNoticeIdRoute: AppNoticeIdRoute,
  AppRecordIdRoute: AppRecordIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  AuditRoute: AuditRoute,
  AddressIdRoute: AddressIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
